spring:
  datasource:
    name: aishuati  #????
    url: jdbc:mysql://114.55.177.229:3306/aishuati?useUnicode=true&useSSL=false&serverTimezone = GMT #url
    username: root  #???
    password: root  #??
    driver-class-name: com.mysql.cj.jdbc.Driver  #???????
  session:
    store-type: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.aishuati.JavaBean #配置实体类

server:
  servlet:
    session:
      cookie:
        secure: true

#fileuploadpath: /home/aishuati-server/files/

#aishuati.upload.files: /home/aishuati-server/files/
aishuati:
  upload:
    files: /home/aishuati-server/files/